# Generated by Django 3.2.8 on 2021-10-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonent_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('abonent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ab.abonent')),
            ],
        ),
    ]
