# Generated by Django 3.2.8 on 2021-10-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='abonent_id',
            new_name='abonent',
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='abonent_id',
        ),
    ]
