# Generated by Django 3.2.8 on 2021-10-22 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ab', '0003_alter_phone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='abonents', to='auth.user', verbose_name='owner of abonent'),
            preserve_default=False,
        ),
    ]
